// Compares two capture runs: semantic hash trace, raw sample equality and
// per-frame SSIM. Writes capture/ssim-report.json and capture/ssim-report.md.
//
// Usage: node capture/compare-runs.mjs --a run-1 --b run-2
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { decodePng } from "./lib/png.mjs";
import { compareImages } from "./lib/ssim.mjs";

const ROOT = new URL("..", import.meta.url).pathname;
const FRAME_MIN = 0.999;

function arg(name, fallback) {
  const index = process.argv.indexOf(`--${name}`);
  return index >= 0 ? process.argv[index + 1] : fallback;
}

const runA = arg("a", "run-1");
const runB = arg("b", "run-2");
const manifest = JSON.parse(readFileSync(join(ROOT, "capture/manifest.json"), "utf8"));

const readTrace = (run) =>
  JSON.parse(readFileSync(join(ROOT, "capture/traces", `${run}.trace.json`), "utf8"));
const readSamples = (run) =>
  readFileSync(join(ROOT, "capture/runs", `${run}.samples.json`), "utf8");

const traceA = readTrace(runA);
const traceB = readTrace(runB);

const hashMismatches = [];
if (traceA.trace.length !== traceB.trace.length) {
  hashMismatches.push({
    tick: null,
    reason: `trace length ${traceA.trace.length} vs ${traceB.trace.length}`,
  });
} else {
  for (let index = 0; index < traceA.trace.length; index += 1) {
    const a = traceA.trace[index];
    const b = traceB.trace[index];
    if (a.tick !== b.tick || a.hash !== b.hash) {
      hashMismatches.push({ tick: a.tick, a: a.hash, b: b.hash });
    }
  }
}

const rawSamplesIdentical = readSamples(runA) === readSamples(runB);

const frames = [];
for (const point of manifest.captures) {
  const name = `tick-${String(point.tick).padStart(5, "0")}.png`;
  const imageA = decodePng(readFileSync(join(ROOT, "capture/frames", runA, name)));
  const imageB = decodePng(readFileSync(join(ROOT, "capture/frames", runB, name)));
  const dimensionsOk =
    imageA.width === manifest.viewport.width && imageA.height === manifest.viewport.height;
  const result = compareImages(imageA, imageB);
  frames.push({
    tick: point.tick,
    label: point.label,
    width: imageA.width,
    height: imageA.height,
    dimensionsOk,
    ssim: Number(result.ssim.toFixed(6)),
    minWindow: Number(result.minWindow.toFixed(6)),
    identical: result.identical,
    diffPixels: result.diffPixels,
    maxChannelDiff: result.maxChannelDiff,
  });
  process.stdout.write(
    `  tick ${String(point.tick).padStart(5)} ${result.ssim.toFixed(6)} ${
      result.identical ? "byte-identical" : `${result.diffPixels} px differ`
    }\n`,
  );
}

const ssimValues = frames.map((frame) => frame.ssim);
const summary = {
  runA,
  runB,
  frames: frames.length,
  hashSamples: traceA.trace.length,
  hashTraceIdentical: hashMismatches.length === 0,
  rawSamplesIdentical,
  byteIdenticalFrames: frames.filter((frame) => frame.identical).length,
  dimensionsOk: frames.every((frame) => frame.dimensionsOk),
  meanSsim: Number((ssimValues.reduce((a, b) => a + b, 0) / ssimValues.length).toFixed(6)),
  minSsim: Number(Math.min(...ssimValues).toFixed(6)),
  frameThreshold: FRAME_MIN,
  pass:
    hashMismatches.length === 0 &&
    rawSamplesIdentical &&
    frames.every((frame) => frame.dimensionsOk && frame.ssim >= FRAME_MIN),
};

writeFileSync(
  join(ROOT, "capture/ssim-report.json"),
  `${JSON.stringify({ summary, hashMismatches, frames }, null, 2)}\n`,
);

const rows = frames
  .map(
    (frame) =>
      `| ${frame.tick} | ${frame.label} | ${frame.width}×${frame.height} | ${frame.ssim.toFixed(
        6,
      )} | ${frame.identical ? "yes" : `no (${frame.diffPixels} px, max Δ${frame.maxChannelDiff})`} |`,
  )
  .join("\n");

writeFileSync(
  join(ROOT, "capture/ssim-report.md"),
  `<!-- generated by capture/compare-runs.mjs -->\n` +
    `| tick | label | size | SSIM (${runA} vs ${runB}) | byte-identical |\n` +
    `|---:|---|---|---:|---|\n${rows}\n`,
);

console.log(JSON.stringify(summary, null, 2));
process.exit(summary.pass ? 0 : 1);
